DROP DATABASE IF EXISTS test2;
CREATE DATABASE test2;
USE city;
DROP TABLE IF EXISTS city;
CREATE TABLE IF NOT EXISTS city(
  id INT PRIMARY KEY AUTO_INCREMENT,
  country VARCHAR(10) NOT NULL,
  province VARCHAR(10),
  city VARCHAR(10) NOT NULL
)ENGINE=InnoDB charset=utf8;